name: Create tag
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
        env:
          TZ: 'Asia/Tokyo'
      - name: Create Tag
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
          git tag "v${{ env.CURRENT_DATETIME }}"
          git push origin "v${{ env.CURRENT_DATETIME }}"
        env:
          USER_NAME: bot
          USER_EMAIL: bot@example.com
      - name: Create Release Tag And Note
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        uses: release-drafter/release-drafter@v5
        with:
          tag_name: "v${{ env.CURRENT_DATETIME }}"
          name: Release "v${{ env.CURRENT_DATETIME }}"
          publish: true
